### ISSUE TITLE
Album scrobbles wrong

### ISSUE THREAD

**Issue by hans-juergen** [cgravolet/scroblr#97] opened 2015-09-13 08:26 UTC
Hi, I'm testing scroblr with Chrome 45 on Windows 7 at the moment with Jango and noticed that the album identification goes wrong: the scrobble takes the next album in the radio track list, e.g. the track "Feel Like Makin' Love" by Bad Company from their "10 From 6" album has the wrong album "Skynyrd's Innards" by Lynyrd Skynyrd now shown in my Last.fm scrobble library. This album came next after Bad Company with the track "Call Me the Breeze", but was shown correctly on Jango as well as the one from Bad Company. So it looks like scroblr gets the album wrong, not Jango, and I have to delete all current scrobbles with scroblr now.

**Comment by cgravolet** [comment] 2016-03-26 13:26
Duplicate of issue #26

**Closed by cgravolet** 2016-03-26 13:26 UTC
